### ISSUE TITLE
how to plot different colors for bigwig files when y axis is less than 0

### ISSUE THREAD

**Issue by jiangshan529** [GangCaoLab/CoolBox#100]
hi, currently, when I plot a bigwig track I can only choose one color. However, when I need to plot insulation bigwig tracks, I need to set two different color for values greater than 0 or smaller than 0. How to plot different color for one bigwig file? Thanks!

The current one I got is like this, I want values greater than 0 be blue.
![image](https://github.com/GangCaoLab/CoolBox/assets/75197626/c38b841e-b7ef-42de-a196-6fea41259ad9)

**Comment by Nanguage** [comment]
Hi, you can use the `threshold_color` parameter of the `BigWig` class, see https://gangcaolab.github.io/CoolBox/api.html#coolbox.core.track.BigWig

**Comment by jiangshan529** [comment]
> Hi, you can use the `threshold_color` parameter of the `BigWig` class, see https://gangcaolab.github.io/CoolBox/api.html#coolbox.core.track.BigWig

Thanks! Like this one: frame = XAxis() + \
        BigWig(f"{DATA_DIR}/bigwig_{RANGE_MARK}.bw") + \
        Color("#ce00ce") + TrackHeight(5) + \
        MinValue(0) + MaxValue(50),

How should I write `threshold_color` parameter, I mean especially for the upper case and little case. I have tried some, but they are not defined.

**Comment by Nanguage** [comment]
Like this: BigWig(xxx, threshold_color=xxx)

**Comment by jiangshan529** [comment]
Thank you!

**Comment by jiangshan529** [comment]
> Like this: BigWig(xxx, threshold_color=xxx)

hi, can I use coolbox to plot hic file off diagnol, like this:
![image](https://github.com/user-attachments/assets/b63b0357-f552-4068-8b25-d56b05771ba4)

**Comment by Nanguage** [comment]
Yes, you can take a look to see if this is what you want. https://gangcaolab.github.io/CoolBox/_gallery/joint_view.html

**Comment by jiangshan529** [comment]
> Yes, you can take a look to see if this is what you want. https://gangcaolab.github.io/CoolBox/_gallery/joint_view.html
hi, thanks! I have tried and I want to plot a region of x:y=4:1, but the plot is in default a squre, can I adjust the plot shape? other than changing in adobe illustrator. Thanks!
![image](https://github.com/user-attachments/assets/8c561cd6-b4b0-4e67-ac6d-0321f6eecaab)
