### ISSUE TITLE
Feature request: colored arcs

### ISSUE THREAD

**Issue by iamjli** [GangCaoLab/CoolBox#2]
I don't believe it is possible to specify the color of individual arcs, correct? I'm working with a dataset in which chromatin interactions were measured from several conditions, and this would be a nice feature to have. 

Awesome package by the way!

**Comment by Nanguage** [comment]
Actually, arcs track support specify color, just pass `color="..."` to `Arcs`, like:
![image](https://user-images.githubusercontent.com/14010939/61575324-d98eb680-aafc-11e9-893f-cd988c03512e.png)
Or use `Color` feature, like:
![image](https://user-images.githubusercontent.com/14010939/61575336-fc20cf80-aafc-11e9-8eaf-e8237c967acc.png)
You can get the result like this:
![image](https://user-images.githubusercontent.com/14010939/61575347-18247100-aafd-11e9-95f5-897bc79be5cc.png)

**Comment by iamjli** [comment]
I meant different colors within a track.

**Comment by Nanguage** [comment]
Okay, thanks for your suggestion. It can implemented with Arcs coverage, I will do that.

**Comment by iamjli** [comment]
Awesome, thanks @Nanguage !

**Comment by Nanguage** [comment]
Hi, I have updated CoolBox these days. Now in the new version(>= 0.2.2), you can use ArcsCoverage to
achieve this effect, see this [example](https://gangcaolab.github.io/CoolBox/_gallery/arcs_cov.html).

Note that in new version, the Arcs input format changed to BEDPE or .pairs file.

**Comment by Nanguage** [comment]
Here is another example to use different colors with cmap https://gangcaolab.github.io/CoolBox/_gallery/arcs_style.html#Color
