### ISSUE TITLE
undesired bed plot

### ISSUE THREAD

**Issue by zhqu1148980644** [GangCaoLab/CoolBox#20]
1.  TrackHeight seems doesn't work in joint view mode
2. overlapping in bed plot(does not relate to jointview)

```python
# Import coolbox
import sys
sys.path.insert(0, "../")
from coolbox.api import *
DATA_DIR = f"../tests/test_data"
test_interval = "chr9:4000000-6000000"
test_itv = test_interval.replace(':', '_').replace('-', '_')

cool1 = Cool(f"{DATA_DIR}/cool_{test_itv}.mcool", cmap="JuiceBoxLike", color_bar=False)

with TrackHeight(1):
    frame_bottom = XAxis() + \
        GTF(f"{DATA_DIR}/gtf_{test_itv}.gtf", length_ratio_thresh=0.005) + TrackHeight(6) + Title("GTF Annotation") + \
        Spacer(1) + \
        BED(f"{DATA_DIR}/bed_{test_itv}.bed") + TrackHeight(10) + Title("BED Annotation")

track_center = cool1


jv = JointView(center=track_center, bottom=frame_bottom)
bsr = Browser(jv)
bsr.goto("chr9:4000000-5500000")
bsr.show()
```

![image](https://user-images.githubusercontent.com/29366130/103454529-0c902e80-4d20-11eb-8c6c-b28611969959.png)

**Comment by Nanguage** [comment]
For the BED problem, actually the code is from the pyGenomeTrack, it's can't not handle label position correctly. In other hand, the GTF plot using the dna_features_viewer package can do this correctly, but it's hard to draw the "fish bone" like structure(to show the intron and exon). The BED code is so long and not wraped well. Maybe we should have some time to read it's code and also dna_features_viewer to solve this.

And here also have the problem like the issue #21 , here also should seprate the gene ploting layer for other track to reuse in the future or let user to custom.

**Comment by Nanguage** [comment]
Fixed
