### ISSUE TITLE
Reuse plot codes of arcs, hicpeaks

### ISSUE THREAD

**Issue by zhqu1148980644** [GangCaoLab/CoolBox#21]
The data format of inputs of `Arcs` and `Hicpeaks` are very similar, if there is a way to reuse the plotting code in custom tracks instead of creating an intermediate bed/pairs file.

It's common to generate python data like `[(start, end), ...]` when calling custom loops in python.

And this situation is quite general, users only care about how to produce the final loop results(representation of ranges) for a specific genomic range.

possible solutions:
- extract plot code outside of each track,
- move plot code(may have different types but are in similar format) down into the base class, and upper classes handle how to convert the raw data(bedpe/pairs/python object) into inputs of plot function in the base class.

**Comment by Nanguage** [comment]
Yes indeed, the arcs and hicpeaks has similar data structure, just different form of visualization. It's need some intermediate representation, maybe the IntervalTree or pandas.Dataframe is suitable for this, I prefer the Dataframe. It can fast extact the data and can directly store to the csv/tsv file. 

For solution, I prefer the second, just like we do in the [hicmat.plot](https://github.com/GangCaoLab/CoolBox/blob/master/coolbox/core/track/hicmat/plot.py) and [hist.plot](https://github.com/GangCaoLab/CoolBox/blob/master/coolbox/core/track/hist/plot.py).
User just inherit them to use, compare to the first solution, it's keep some uniformity in design.

**Comment by zhqu1148980644** [comment]
9ea0c8b63b53e1551a0d7baf81ad4642a0aee002
