### ISSUE TITLE
Doc inheritance

### ISSUE THREAD

**Issue by Nanguage** [GangCaoLab/CoolBox#23]
https://github.com/GangCaoLab/CoolBox/commit/bda22d34fcd913a5a62caeb49b0bc071f49cb54d 

Maybe it's canbe implement by text parsing and replace during inheritance to overwrite or add parameters?

**Comment by zhqu1148980644** [comment]
I searched on google and found that the `numpydoc` can do the parsing job. [example](https://stackoverflow.com/questions/37929851/how-can-i-parse-a-numpydoc-docstring-and-access-components)

**Comment by zhqu1148980644** [comment]
8e5abd1dd8753fee4812c5b010095d286766b104
