### ISSUE TITLE
docker: invalid reference format: repository name must be lowercase.

### ISSUE THREAD

**Issue by mdozmorov** [GangCaoLab/CoolBox#28]
Hi. I tried to run CoolBox using Docker as [per instructions](https://gangcaolab.github.io/CoolBox/installation.html#docker). It pulls, but when running it I'm getting:
````
$ docker run -ti -v $(pwd):/data -p 9000:8888 nanguage/coolbox
docker: invalid reference format: repository name must be lowercase.
````
Running other containers works fine. And, I've installed CoolBox into the conda environment. Suggesting to check what's going on with the Docker image.

**Comment by zhqu1148980644** [comment]
Hi, I can't reproduce this issue, how about trying this one: `docker run -ti -v "$(pwd):/data" -p 9000:8888 nanguage/coolbox:latest` [ref](https://stackoverflow.com/a/52818152/10336496)

**Comment by Nanguage** [comment]
Hi, I also can't reproduce this. What's the OS and shell? 

In PowerShell, `${pwd}` instead of `$(pwd)` should be used, according to [this](https://stackoverflow.com/questions/45682010/docker-invalid-reference-format).

**Comment by mdozmorov** [comment]
It was fixed after the laptop restart. Apparently, some software glitch. Rarely happen on a Mac, but does happen. 
Thanks for the great tool, the code examples in the CoolBox Gallery are particularly helpful!
