### ISSUE TITLE
hieght of BED track is too large

### ISSUE THREAD

**Issue by zhqu1148980644** [GangCaoLab/CoolBox#33]
This occurs when there are only a few rows of the overlapping regions.

![image](https://user-images.githubusercontent.com/29366130/116235765-d5430300-a790-11eb-9929-4aee971faa49.png)

**Comment by Nanguage** [comment]
Now, bed file support 'auto' height, can increase the height according to the number of rows in view.

https://gangcaolab.github.io/CoolBox/_gallery/dna_features.html#layout
