### ISSUE TITLE
UnicodeDecodeError in Browser with parameter img_format different than svg.

### ISSUE THREAD

**Issue by eafyounian** [GangCaoLab/CoolBox#37]
The Browser class has `img_format='svg'` set. With `svg` it works just fine and I can make screenshots, but when I replace it with e.g. `png` or `jpeg` and use `bsr.save()` to save the screenshot, I get the following error:
```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
path/to/anaconda3/envs/coolbox/lib/python3.9/site-packages/traitlets/traitlets.py in validate(self, obj, value)
   2179             try:
-> 2180                 return value.decode('ascii', 'strict')
   2181             except UnicodeDecodeError:

UnicodeDecodeError: 'ascii' codec can't decode byte 0x89 in position 0: ordinal not in range(128)

During handling of the above exception, another exception occurred:

TraitError                                Traceback (most recent call last)
...
``` 
I am using `Python 3.9.4` and `coolbox` version `0.3.3` and the coolbox environment was built via `environment.yml` file in the respository.

**Comment by zhqu1148980644** [comment]
Hi, thanks for reporting this bug. I didn't write this part. After I checked out the source code, I found that the `img_format` parameter has nothing to do with the logic of saving figure.

https://github.com/GangCaoLab/CoolBox/blob/eaf61db467f6452b24d7d99ddab71934bbe9d495/coolbox/core/browser/base.py#L251-L257

A possible solution is to fetch the `Figure` object from `frame.show()`, then use it as norml.

![image](https://user-images.githubusercontent.com/29366130/118982997-8d3d8780-b9ae-11eb-97f5-408da1f2ec37.png)

**Comment by Nanguage** [comment]
Hi,

Thanks for reporting bug. Actually my unclear doc-string mis-leaded you.
This parameter is for change the image formats displayed in the frame within the web-page, it's not for saving.
If you want to change the saving format, in addition to https://github.com/GangCaoLab/CoolBox/issues/37#issuecomment-845097913, you can also directly change the suffix of the path parameter of `bsr.save`, like this:

![image](https://user-images.githubusercontent.com/14010939/119078644-2b6e3380-ba29-11eb-8122-a9f6f6d107f3.png)

I have changed the doc-string:

https://github.com/GangCaoLab/CoolBox/blob/31e2770a99a8ef07d7c747dca1139d8144715a92/coolbox/core/browser/base.py#L46-L48

https://github.com/GangCaoLab/CoolBox/blob/31e2770a99a8ef07d7c747dca1139d8144715a92/coolbox/core/browser/base.py#L252-L257

Thanks!

**Comment by eafyounian** [comment]
Great! Thank you for quick reply and the fix! I guess we can assume that this issue is now resolved! :)
