### ISSUE TITLE
Changing resolution for hic matrix is not working

### ISSUE THREAD

**Issue by tuomovirtanen** [GangCaoLab/CoolBox#38]
It seems that changing the resolution parameter doesn't change anything and the DotHiC always opts for the "auto" option. This is visible also in the example provided in the gallery (https://gangcaolab.github.io/CoolBox/_gallery/reso_normalize.html). There appears to be no difference between 10kb and 25kb resolution.

**Comment by Nanguage** [comment]
Hi, thanks for reporting bug!

I think this has beed fixed in new version(0.3.8):
![image](https://user-images.githubusercontent.com/14010939/120146157-3be79080-c217-11eb-8c0c-46ce4602f168.png)

Please update from PyPI or GitHub source code: https://gangcaolab.github.io/CoolBox/installation.html

**Comment by zhqu1148980644** [comment]
Let us know if there are still problems.
