### ISSUE TITLE
Possibility to change positional argument in `coolbox.core.track.HiCMat()` to named argument

### ISSUE THREAD

**Issue by eafyounian** [GangCaoLab/CoolBox#39]
Hi!

Many other functions in `coolbox` have the named argument `file`. I was wondering if it is possible to change  `coolbox.core.track.HiCMat()`'s signature such that it accepts the the named argument `file` instead of `file_or_hicmat` which is a positional argument?

I am asking because, this helps me to create a track by creating a dictionary e.g. by reading a YAML config file and then unpack the dictionary as the arguments. Currently, this works e.g. for `BED()` but not for `HiCMat()`:

This works:

```
frame = XAxis() + BED(**track_params) 
frame.plot(TEST_RANGE)
```

But this:

```
frame = XAxis() + HiCMat(**track_params) 
frame.plot(TEST_RANGE)
```
does not work and results in 

`TypeError: HiCMat() missing 1 required positional argument: 'file_or_hicmat'`

The way I am bypassing the issue currently, is like this:

````
file_name = track_params.pop('file')
frame = XAxis() + HiCMat(file_name, **track_params)
frame.plot(TEST_RANGE)
``` 

Thank you in advance for checking this out and for the "cool" tool! :)

**Comment by zhqu1148980644** [comment]
Hi, I changed the parameter name to `file` now, Does it works now?

**Comment by eafyounian** [comment]
Perfect! I tested it an it works great! Thank you for very quick reply and the fix! :) I guess we can assume that this issue is now resolved! :)
