### ISSUE TITLE
CoolBox doesn't work with for loops?

### ISSUE THREAD

**Issue by gabedolpten** [GangCaoLab/CoolBox#43]
Hi, I have a certain code which runs well:
```
    frame = (XAxis() + HiCMat(f"mat.mcool", height=6))
    frame.plot(chrom, s, e)
```
I am now trying to run this code for several different regions:
```
for i in range(10):    
    frame = (XAxis() + HiCMat(f"mat.mcool", height=6))
    frame.plot(chrom, s, e)
```
However, nothing is produced. Do you know why this is? Even this does not work:
```
for i in range(11):    
    frame = (XAxis() + HiCMat(f"mat.mcool", height=6))
    frame.plot(chrom, s, e)
```

**Comment by gabedolpten** [comment]
Nevermind, frame.plot() returns a matplotlib figure which can be saved with .savefig()

**Comment by zhqu1148980644** [comment]
Another option directly show in notebook:
![image](https://user-images.githubusercontent.com/29366130/120255591-e797eb80-c2be-11eb-9c85-acc49b28dc10.png)
