### ISSUE TITLE
Citing CoolBox

### ISSUE THREAD

**Issue by eafyounian** [GangCaoLab/CoolBox#46]
Hi! I would like to cite CoolBox in our article. Is the following the latest reference to your tool?

[CoolBox: A flexible toolkit for visual analysis of genomics data](https://www.biorxiv.org/content/10.1101/2021.04.15.439923v1.full)

**Comment by zhqu1148980644** [comment]
@Nanguage

**Comment by Nanguage** [comment]
Yes, it's the latest reference until now. Thanks for your citation!

**Comment by eafyounian** [comment]
Great! Thank you! :)

**Comment by eafyounian** [comment]
CoolBox is now published as _CoolBox: a flexible toolkit for visual analysis of genomics data_ available at: https://doi.org/10.1186/s12859-021-04408-w

```
Xu, W., Zhong, Q., Lin, D. et al. CoolBox: a flexible toolkit for visual analysis of genomics data. BMC Bioinformatics 22, 489 (2021).
```
