### ISSUE TITLE
Changing the way a track looks

### ISSUE THREAD

**Issue by c-guzman** [GangCaoLab/CoolBox#49]
Is there a way to change the way a coverage track looks? 

For example, CoolBox output looks like: https://imgur.com/a/dgk1Hdr (top)

This is great for most types of sequencing data, including ChIP/ATAC/GRO, etc. However, for 5' data which I am working with, the visualization isn't ideal.

Ideally, I want my track to look like a histogram as follows:  https://imgur.com/a/dgk1Hdr (bottom)

Is this possible?

PS: Additionally, is there a way to change the x-axis length? To show complete numbers instead of Kb? In my case my chromosome lengths are only 200bp, so everything shows up at 0 Kb.

**Comment by zhqu1148980644** [comment]
If this suits your requirement? https://github.com/GangCaoLab/CoolBox/pull/31

**Comment by c-guzman** [comment]
This style appears to suit my requirements much more, but it's hard to say since it doesn't look like it's included yet. Or at least it doesn't work on BedGraph() objects.

**Comment by zhqu1148980644** [comment]
> This style appears to suit my requirements much more, but it's hard to say since it doesn't look like it's included yet. Or at least it doesn't work on BedGraph() objects.

It should work, since BedGraph is subclassed from Hist

**Comment by c-guzman** [comment]
Odd. I tried:

```
frame = XAxis() + \
        BedGraph(bdg_path, style='stairsfilled') + \
        Color("black") + TrackHeight(2) + Title("5' MPRA (Original Pool Rep1)")
```

And my resulting chart looked the exact same

**Comment by zhqu1148980644** [comment]
If you are using the latest version in github?

**Comment by c-guzman** [comment]
Running `coolbox.__version__` results in `'0.3.3'`

**Comment by c-guzman** [comment]
Beautiful! https://imgur.com/a/PlYE1dx

Should I start a new issue for my XAxis question? Instead of kilobases i'd like simply bases since my sequence lengths are less than 1000bp.

**Comment by zhqu1148980644** [comment]
> Beautiful! https://imgur.com/a/PlYE1dx
> 
> Should I start a new issue for my XAxis question? Instead of kilobases i'd like simply bases since my sequence lengths are less than 1000bp.

sure.😀
