### ISSUE TITLE
How is insulation score calculation performed?

### ISSUE THREAD

**Issue by gabedolpten** [GangCaoLab/CoolBox#55]
Would it be possible to export the insulation score to a bigwig?

**Comment by zhqu1148980644** [comment]
you can check the source code here: https://github.com/GangCaoLab/CoolBox/blob/6432254cc343ed35e4578eb2d5662cfc59ac09db/coolbox/core/track/hist/hicfeature.py#L73

it's calculated the same way as the original paper.

**Comment by at-katsu** [comment]
Not sure if I missed it, but which original paper are you referring to? Thanks.

**Comment by Nanguage** [comment]
This is the original paper of the IS method:

> Emily Crane 2015. Condensin-driven remodelling of X chromosome topology during dosage compensation
