### ISSUE TITLE
Couldn't change bin width of histgram

### ISSUE THREAD

**Issue by zhouzhendiao** [GangCaoLab/CoolBox#65]
I have a bed with overlap regions, when I transfer bed file to bedgraph , bigwig format  and plot by `BED()`,  `BedGraph()`, `BigWig`：

```
frame = XAxis() + \
        BED(probe_file, display='stacked') + \
        BedGraph(bg) + \
        BigWig(bwfile, min_value=0) + \

frame.plot(reg)
````

![image](https://user-images.githubusercontent.com/12294679/150485016-e1044af3-cf14-42fc-b26c-16d5e99875e7.png)

I want those histograms with bin width = 1. However, I couldn't find the corresponding parameters.

By the way, there are 4 bed records in this region, but only 3 ploted.

**Comment by Nanguage** [comment]
What means "bin width = 1"?  And can you provide your bed file?

**Comment by zhouzhendiao** [comment]
> What means "bin width = 1"? And can you provide your bed file?

I want to plot the histogram with 1 bp resolution.

For example, in `seaborn.histplot`

````
sns.histplot(data=penguins, x="flipper_length_mm", binwidth=3)
````

![histplot_5_0](https://user-images.githubusercontent.com/12294679/150491741-8ce6342b-7be9-4628-999b-3be883f8c598.png)

**Comment by zhouzhendiao** [comment]
> What means "bin width = 1"? And can you provide your bed file?

my bed:

```
1       11854395        11854494
1       11854420        11854519
1       11854445        11854544
1       11854470        11854569
1       11856297        11856396
1       11856322        11856421
1       11856347        11856446
1       11856372        11856471
```
bedgraph:
```
1       11854395        11854420        1
1       11854420        11854445        2
1       11854445        11854470        3
1       11854470        11854494        4
1       11854494        11854519        3
1       11854519        11854544        2
1       11854544        11854569        1
1       11856297        11856322        1
1       11856322        11856347        2
1       11856347        11856372        3
```

The bigwig were transferreded from bedgraph by  bedGraphToBigWig.

**Comment by Nanguage** [comment]
The min resolution of BedGraph and BigWig is depend on your input file, in this case, your input resolution is large than 1bp.

**Comment by zhouzhendiao** [comment]
> 

Thanks, but why BedGraph and BigWig plot different ways?  I just transferred the file from BedGraph to Bigwig .

**Comment by Nanguage** [comment]
It's deal to some historical problems, but these two different style has same information. We will set another parameter to control this in future.

**Comment by zhouzhendiao** [comment]
> It's due to some historical problems, but these two different style has same information. We will set another parameter to control this in future.

OK, thanks!
