### ISSUE TITLE
TAD Image generation error

### ISSUE THREAD

**Issue by Zheng19w** [GangCaoLab/CoolBox#82]
cool="./laiwu.mcool"
tads="./laiwu_domains.bed"

coolbox add XAxis - \
add Cool $cool - \
add TADCoverage $tads --border_only True --alpha 1.0 - \
goto "9:40000000-60000000" - \
plot ./test_coolbox.pdf
![image](https://github.com/GangCaoLab/CoolBox/assets/106860091/0195df43-4909-4c60-b34d-d840dfae4abf)

Hello, why is the generated picture not a pyramid shape, as shown in the following picture, looking forward to your reply！

![image](https://github.com/GangCaoLab/CoolBox/assets/106860091/fe729d86-2fee-4067-bcd5-9bcb9ea3215c)

**Comment by Zheng19w** [comment]
![image](https://github.com/GangCaoLab/CoolBox/assets/106860091/59df8f74-c4c7-4d2d-b576-8245ab029514)

**Comment by Nanguage** [comment]
You can specify the matrix style using: `--style='triangular'` parameter to draw the 'pyramid shape' matrix:
```
cool="./laiwu.mcool"
tads="./laiwu_domains.bed"

coolbox add XAxis -
add Cool $cool --style "triangular" -
add TADCoverage $tads --border_only True --alpha 1.0 -
goto "9:40000000-60000000" -
plot ./test_coolbox.pdf

```

**Comment by Zheng19w** [comment]
Thank you for you replay
