### ISSUE TITLE
cool

### ISSUE THREAD

**Issue by Zheng19w** [GangCaoLab/CoolBox#86]
Hello, I have an mcool file, but it contains X and Y sex chromosomes, as well as some scafold. Is there any way to remove them and only keep autosomes 1 to 18
![image](https://github.com/GangCaoLab/CoolBox/assets/106860091/60e772f5-02e8-4bf9-b515-56e81c3bd6ca)

**Comment by zhqu1148980644** [comment]
check [`cooler`](https://github.com/open2c/cooler) project in github for details, they provide API/CLI that can achieve your goal.
