### ISSUE TITLE
Heatmap for tracks

### ISSUE THREAD

**Issue by StarkTS98** [GangCaoLab/CoolBox#93]
Hey, I am new to Coolbox and tried using it for my Bedgraph files. I am working with single-cell dataset where I have the bedgraph/bigwig files for each single cell. I can generate tracks for these but I was wondering if there is any way to create heatmaps of tracks instead of barcharts (similar to the heatmaps feature of IGV). 
I am wanting to generate something like this where each horizontal line is a single cell profile shown as a heatmap. This is a screenshot from igv but I want to use a command line based equivalent for reproducibility:
![image](https://github.com/GangCaoLab/CoolBox/assets/104354986/640066e4-a5ec-4587-84a0-3e3a5dbd3bec)

Thanks in advance. If not by coolbox, is there any other command line based tool

**Comment by Nanguage** [comment]
Hello, this is achievable, but there is currently no built-in implementation. You can try customizing a Track like this yourself, I don't think it's difficult. For information on how to customize a Track, you can refer to here: https://gangcaolab.github.io/CoolBox/custom_elements.html
